fullnameOverride: "prometheus"

alertmanager:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx

    hosts:
    - alertmanager.local.io

    paths:
    - /

grafana:
  ingress:
    enabled: true
    
    annotations:
      kubernetes.io/ingress.class: nginx
    
    hosts:
    - grafana.local.io
    
    path: /
   
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - prometheus.local.io
    paths:
    - /

  prometheusSpec:
    serviceMonitorSelector:
      matchExpressions:
      - key: release
        operator: In
        values:
        - prometheus
        - nginx


kubeApiServer:
  serviceMonitor:
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
